config/routes.rb
Rails.application.routes.draw do
  get 'static_pages/index'
  get 'static_pages/secret'

  devise_for :users

  resources :attendances
  resources :events
  resources :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
   root "static_pages#index"
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  before_action :authenticate_user!, only: [:secret] # This ensures user is signed in for the index action

  # Your controller actions and code here
  def index
  end
  def secret
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/index.html.erb
<div class="pagebody">
  <h1>Welcome to Eventbrite</h1>
  <p>Your one-stop-shop for all events in your city.</p>

  <ul>
    <% if user_signed_in? %>
      <li>
        <%= link_to "Sign out", destroy_user_session_path, method: :delete, data: {turbo_method: :delete} %>
      </li>

      <li>
        Voici ton email : <%= current_user.email %>
      </li>

      <li>
        <%= link_to "Secret page", static_pages_secret_path %>
      </li>

      <li>
       <%= link_to "Edit email / password", edit_user_registration_path %>
      </li>

    <% else %>
      <li>    
        <%= link_to "Sign in", new_user_session_path %>
      </li>

      <li>
        <%= link_to "Sign up", new_user_registration_path %>
      </li>

    <% end %>
  </ul>

  <p>Eventbrite is the number one app for finding events posted by users in your city.</p>

  <% if user_signed_in? %>
    <p>Welcome, <%= current_user.email %>.</p>
  <% end %>
</div>

app/views/static_pages/secret.html.erb
<h1>StaticPages#secret</h1>
<p>Find me in app/views/static_pages/secret.html.erb</p>
<% if user_signed_in? %>
  <p>This is a secret page visible to signed-in users.</p>
<% else %>
  <p>You need to sign in to access this secret page.</p>
<% end %>